# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13visualization.proto\x12\x06src.pb\"K\n\x12ImagePromptRequest\x12\x11\n\tjwt_token\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x0e\n\x06prompt\x18\x03 \x01(\t\"1\n\x13ImagePromptResponse\x12\x1a\n\x12response_to_prompt\x18\x01 \x01(\t2h\n\x14VisualizationService\x12P\n\x15ProcessImageAndPrompt\x12\x1a.src.pb.ImagePromptRequest\x1a\x1b.src.pb.ImagePromptResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'visualization_pb2', _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_IMAGEPROMPTREQUEST']._serialized_start = 31
    _globals['_IMAGEPROMPTREQUEST']._serialized_end = 106
    _globals['_IMAGEPROMPTRESPONSE']._serialized_start = 108
    _globals['_IMAGEPROMPTRESPONSE']._serialized_end = 157
    _globals['_VISUALIZATIONSERVICE']._serialized_start = 159
    _globals['_VISUALIZATIONSERVICE']._serialized_end = 263
# @@protoc_insertion_point(module_scope)
